spring:
  application:
    name: auth-service-api
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:info-cortex-db
      driverClassName: org.h2.Driver
      username: chronus
      password: chronus
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          show-sql: true

server:
  port: 8081
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

logging:
  level:
    com.github.julionet.authservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.hibernate.transaction: DEBUG
    org.hibernate.cache: DEBUG
